# Creates an ECS Cluster in AWS via a CLoud Formation Template
name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: intuit/cfn-deploy@master
      env:
        AWS_REGION: us-east-1
        STACK_NAME: cfn-deploy
        TEMPLATE_FILE: create-ecs-cluster.json
        PARAMETERS_FILE: parameter.json
        CAPABLITIES: CAPABILITY_IAM
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
